### ISSUE TITLE
Error building project on storyboardSetup branch

### ISSUE THREAD

**Issue by sylasprime94** [letsgetthisbreadd/NutriQ#16]
I'm getting this issue saying `foodGif.gif` under the `Image` folder is missing. Did you push it? Please confirm. If not, add, commit, and push it and close this issue. If you did push it and can confirm with a screenshot, please post it as a comment and close this issue. Thanks!

![image](https://user-images.githubusercontent.com/13278314/56084612-4eb66580-5e03-11e9-8bf3-83e9b002cff7.png)

![image](https://user-images.githubusercontent.com/13278314/56084608-3f371c80-5e03-11e9-939e-1b15014a8c5b.png)

**Comment by MikeMcmanus95** [comment]
It seems that Xcode didn't actually copy the FoodGif file from my downloads directory into the project directory when I imported it into the project. Odd, but all has been resolved!
